/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fpoly.core.forms;
import com.fpoly.core.DAO.NhaCungCapDAO;
import com.fpoly.core.models.NhaCungCap;
import java.util.List;
import com.fpoly.core.utils.MsgBox;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author WELCOME
 */
public class NhaCungCapJDialog extends javax.swing.JDialog {
       NhaCungCapDAO dao = new NhaCungCapDAO();
       int row =0;
    /**
     * Creates new form NhaCungCap
     */
    public NhaCungCapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnsua = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        txtdiachi = new javax.swing.JTextField();
        txttenncc = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtseach = new javax.swing.JTextField();
        btnseach = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        btnxuatphieunhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmancc = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        btnxoa = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        banghienthiphieumuon = new javax.swing.JTable();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnsua.setText("Sửa TT mượn");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnsave.setText("Lưu");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm TT mượn");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnhuy.setText("Hủy");
        btnhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyActionPerformed(evt);
            }
        });

        txtdiachi.setText(" ");
        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });

        txttenncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttennccActionPerformed(evt);
            }
        });

        jLabel34.setText("Tên NCC");

        jLabel35.setText("Địa chỉ");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Search");

        txtseach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseachActionPerformed(evt);
            }
        });

        btnseach.setText("Tìm");
        btnseach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseachActionPerformed(evt);
            }
        });

        jLabel37.setText("Từ khóa");

        btnxuatphieunhap.setText("Xuất phiếu nhập");

        jLabel2.setText("MÃ NCC");

        jLabel3.setText("SĐT");

        txtmancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanccActionPerformed(evt);
            }
        });

        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtmancc)
                                    .addComponent(txttenncc, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtseach, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnseach)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(btnxuatphieunhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtseach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(btnseach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addGap(216, 216, 216))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnthem)
                                .addGap(26, 26, 26)
                                .addComponent(btnsua))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(txttenncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtmancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(9, 9, 9)
                        .addComponent(btnsave)
                        .addGap(37, 37, 37)
                        .addComponent(btnxoa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(btnxuatphieunhap)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        banghienthiphieumuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NCC", "Tên", "SĐT", "Địa Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        banghienthiphieumuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banghienthiphieumuonMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(banghienthiphieumuon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        update();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        update();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        insert();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyActionPerformed
         reset();
    }//GEN-LAST:event_btnhuyActionPerformed

    private void btnseachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseachActionPerformed
        search();
    }//GEN-LAST:event_btnseachActionPerformed

    private void txtmanccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanccActionPerformed

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txttennccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttennccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttennccActionPerformed

    private void banghienthiphieumuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banghienthiphieumuonMouseClicked
        // TODO add your handling code here:
         this.row = banghienthiphieumuon.rowAtPoint(evt.getPoint());
         edit();
        
    }//GEN-LAST:event_banghienthiphieumuonMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void txtseachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhaCungCapJDialog dialog = new NhaCungCapJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable banghienthiphieumuon;
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnseach;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxuatphieunhap;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtmancc;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtseach;
    private javax.swing.JTextField txttenncc;
    // End of variables declaration//GEN-END:variables
    private List<NhaCungCap> selectAll (){
        try {
            return dao.selectAll();
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "lỗi truy cập dữ liệu");
        }
           return null;
    
    }

    private void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) banghienthiphieumuon.getModel();
    model.setRowCount(0); // Xóa hết các dòng trong bảng hiện tại

    // Gọi phương thức selectAll để lấy danh sách nhà cung cấp từ CSDL
    List<NhaCungCap> list = selectAll(); // Sử dụng phương thức selectAll để lấy danh sách

    if (list != null) {
        for (NhaCungCap ncc : list) {
            Object[] row = {
                ncc.getMaNCC(),
                ncc.getTenNCC(),
                ncc.getSDT(),
                ncc.getDiaChi()
            };
            model.addRow(row); // Thêm một dòng vào bảng với dữ liệu của nhà cung cấp ncc
        }
    } else {
        MsgBox.alert(this, "Không có dữ liệu để hiển thị");
    }
}
    
    private void display(NhaCungCap ncc) {
        txtmancc.setText(ncc.getMaNCC());
        txttenncc.setText(ncc.getTenNCC());
        txtdiachi.setText(ncc.getDiaChi());
        txtsdt.setText(ncc.getSDT());
}

void edit() {
    String maNCC = (String) banghienthiphieumuon.getValueAt(this.row, 0);
    NhaCungCap ncc = dao.selectById(maNCC);
    if (ncc != null) {
        display(ncc);
    }
}

void insert() {
    String maNCC = txtmancc.getText();
    String tenNCC = txttenncc.getText();
    String diaChi = txtdiachi.getText();
    String sdt = txtsdt.getText();

    // Kiểm tra xem các trường có bị bỏ trống hay không
    if (maNCC.isEmpty() || tenNCC.isEmpty() || diaChi.isEmpty() || sdt.isEmpty()) {
        MsgBox.alert(this, "Vui lòng điền đầy đủ thông tin!");
        return;
    }

    // Tạo đối tượng NhaCungCap mới
    NhaCungCap ncc = new NhaCungCap();
    ncc.setMaNCC(maNCC);
    ncc.setTenNCC(tenNCC);
    ncc.setDiaChi(diaChi);
    ncc.setSDT(sdt);

    // Gọi phương thức insert từ lớp NhaCungCapDAO
    try {
        dao.insert(ncc);
        MsgBox.alert(this, "Thêm nhà cung cấp thành công!");
        fillToTable(); // Cập nhật lại bảng
    } catch (Exception e) {
        e.printStackTrace();
        MsgBox.alert(this, "Lỗi khi thêm nhà cung cấp!");
    }
}

void update() {
    String maNCC = txtmancc.getText();
    String tenNCC = txttenncc.getText();
    String diaChi = txtdiachi.getText();
    String sdt = txtsdt.getText();

    // Kiểm tra xem các trường có bị bỏ trống hay không
    if (maNCC.isEmpty() || tenNCC.isEmpty() || diaChi.isEmpty() || sdt.isEmpty()) {
        MsgBox.alert(this, "Vui lòng điền đầy đủ thông tin!");
        return;
    }

    // Tạo đối tượng NhaCungCap mới với thông tin đã cập nhật
    NhaCungCap ncc = new NhaCungCap();
    ncc.setMaNCC(maNCC);
    ncc.setTenNCC(tenNCC);
    ncc.setDiaChi(diaChi);
    ncc.setSDT(sdt);

    // Gọi phương thức update từ lớp NhaCungCapDAO
    try {
        dao.update(ncc);
        MsgBox.alert(this, "Sửa thông tin nhà cung cấp thành công!");
        fillToTable(); // Cập nhật lại bảng
    } catch (Exception e) {
        e.printStackTrace();
        MsgBox.alert(this, "Lỗi khi sửa thông tin nhà cung cấp!");
    }
}

void delete() {
    String maNCC = txtmancc.getText();
    // Kiểm tra xem mã nhà cung cấp có bị bỏ trống hay không
    if (maNCC.isEmpty()) {
        MsgBox.alert(this, "Vui lòng nhập mã nhà cung cấp để xóa!");
        return;
    }
    // Xác nhận lại việc xóa
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa nhà cung cấp này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    // Gọi phương thức delete từ lớp NhaCungCapDAO
    try {
        dao.delete(maNCC);
        MsgBox.alert(this, "Xóa nhà cung cấp thành công!");
        fillToTable(); // Cập nhật lại bảng
    } catch (Exception e) {
        e.printStackTrace();
        MsgBox.alert(this, "Lỗi khi xóa nhà cung cấp!");
    }
}

void reset() {
    txtmancc.setText("");
    txttenncc.setText("");
    txtdiachi.setText("");
    txtsdt.setText("");
}
void search() {
    // Lấy từ khóa tìm kiếm từ trường nhập liệu
    String keyword = txtseach.getText();

    // Kiểm tra xem từ khóa có bị bỏ trống hay không
    if (keyword.isEmpty()) {
        MsgBox.alert(this, "Vui lòng nhập từ khóa để tìm kiếm!");
        return;
    }

    // Gọi phương thức tìm kiếm từ lớp NhaCungCapDAO
    try {
        List<NhaCungCap> list = dao.searchByKeyword(keyword);
        fillToTablesearch(list); // Cập nhật lại bảng với danh sách kết quả tìm kiếm
    } catch (Exception e) {
        e.printStackTrace();
        MsgBox.alert(this, "Lỗi khi tìm kiếm nhà cung cấp!");
    }
}

private void fillToTablesearch(List<NhaCungCap> list) {
    DefaultTableModel model = (DefaultTableModel) banghienthiphieumuon.getModel();
    model.setRowCount(0);
    for (NhaCungCap ncc : list) {
        Object[] row = {
            ncc.getMaNCC(),
            ncc.getTenNCC(),
            ncc.getDiaChi(),
            ncc.getSDT()
        };
        model.addRow(row);
    }
}

}
